# Generated by Django 4.2.30 on 2026-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0002_admin_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaylist',
            name='batch_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaylist',
            name='batch_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaylist',
            name='batch_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='batch_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='batch_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='batch_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
