# Generated by Django 4.2.30 on 2026-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0004_renumber_rights_to_27xxxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentaccount',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
