# Generated by Django 4.2.30 on 2026-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0007_historicalfspmapping_fspmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaylist',
            name='destination',
            field=models.CharField(choices=[('MUSE', 'MUSE'), ('GEPG', 'GePG')], default='MUSE', max_length=10),
        ),
        migrations.AddField(
            model_name='paylist',
            name='destination',
            field=models.CharField(choices=[('MUSE', 'MUSE'), ('GEPG', 'GePG')], default='MUSE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='paylist',
            index=models.Index(fields=['destination'], name='tasaf_paylist_dest_idx'),
        ),
    ]
