# Generated by Django 4.2.30 on 2026-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0008_historicalpaylist_destination_paylist_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaylist',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaylistitem',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylistitem',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
