# Generated by Django 4.2.30 on 2026-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0016_muse_settings_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaylist',
            name='muse_msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='muse_msg_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
