# Generated by Django 4.2.30 on 2026-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0020_unapplied_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaylistitem',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='paylistitem',
            name='final_status',
        ),
        migrations.AddField(
            model_name='historicalpaylist',
            name='muse_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaylist',
            name='muse_status_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='muse_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paylist',
            name='muse_status_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaylist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('SUBMITTED', 'SUBMITTED'), ('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('SENT_TO_BANK', 'SENT_TO_BANK'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpaylistitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('UNAPPLIED', 'UNAPPLIED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreturnfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('UNAPPLIED', 'UNAPPLIED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paylist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('SUBMITTED', 'SUBMITTED'), ('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('SENT_TO_BANK', 'SENT_TO_BANK'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paylistitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('UNAPPLIED', 'UNAPPLIED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('UNAPPLIED', 'UNAPPLIED')], max_length=20),
        ),
    ]
