# Generated by Django 4.2.30 on 2026-09-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0021_muse_batch_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmusesettings',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='musesettings',
            name='currency_code',
        ),
    ]
