# Generated by Django 4.2.30 on 2026-09-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasaf_payment', '0023_draft_to_rejected_at_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaylist',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('SUBMITTED', 'SUBMITTED'), ('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('SENT_TO_BANK', 'SENT_TO_BANK'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED'), ('REJECTED_AT_APPROVAL', 'REJECTED_AT_APPROVAL')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='paylist',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('SUBMITTED', 'SUBMITTED'), ('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('SENT_TO_BANK', 'SENT_TO_BANK'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED'), ('REJECTED_AT_APPROVAL', 'REJECTED_AT_APPROVAL')], default='PENDING_APPROVAL', max_length=20),
        ),
    ]
